### ISSUE TITLE
node-gyp build error v8::Value::BooleanValue

### ISSUE THREAD

**Issue by marmelin** [arkenthera/electron-vibrancy#38]
I installed everything for node-gyp, but it still gives errors. This one seems like a code or build-version problem. Does anyone know something about it?

thx in advance

### Error
_With Windows 10 SDK (10.0.19041.0)_
```
Vibrancy.cc
C:\Projects\tmp\hyper-transparent\electron-vibrancy\src\Vibrancy.cc(86,57): 
   error C2660: "v8::Value::BooleanValue": 
   Function does not accept null values 
        [C:\Projects\tmp\hyper-transparent\electron-vibrancy\build\Vibrancy.vcxproj]
C:\Users\lochmar\AppData\Local\node-gyp\Cache\15.1.0\include\node\v8.h(2904,8): 
   message : See declaration of  "v8::Value::BooleanValue" 
        [C:\Projects\tmp\hyper-transparent\electron-vibrancy\build\Vibrancy.vcxproj]
```

<details><summary>Complete node-gyp build error</summary> 
```
C:\Projects\tmp\hyper-transparent\electron-vibrancy>npm install

> electron-vibrancy@0.1.3 install
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.1.0 | win32 | x64
gyp info find Python using Python version 3.9.0 found at "C:\...\Python\Python39\python.exe"
gyp info find VS using VS2019 (16.8.30711.63) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - found Windows 10 SDK (10.0.19041.0)
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\...\Python\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Projects\\tmp\\hyper-transparent\\electron-vibrancy\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Projects\\tmp\\hyper-transparent\\electron-vibrancy\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Projects\\tmp\\hyper-transparent\\electron-vibrancy\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\..\\AppData\\Local\\node-gyp\\Cache\\15.1.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\..\\AppData\\Local\\node-gyp\\Cache\\15.1.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Projects\\tmp\\hyper-transparent\\electron-vibrancy\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\..\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\15.1.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Projects\\tmp\\hyper-transparent\\electron-vibrancy',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Projects\\tmp\\hyper-transparent\\electron-vibrancy\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "-m" hinzufügen.
  Vibrancy.cc
C:\Projects\tmp\hyper-transparent\electron-vibrancy\src\Vibrancy.cc(86,57): error C2660: "v8::Value::BooleanValue": Funktion akzeptiert keine 0 Argumente [C:\Projects\tmp\hyper-transpare 
nt\electron-vibrancy\build\Vibrancy.vcxproj]
C:\Users\lochmar\AppData\Local\node-gyp\Cache\15.1.0\include\node\v8.h(2904,8): message : Siehe Deklaration von "v8::Value::BooleanValue" [C:\Projects\tmp\hyper-transparent\electron-vibr 
ancy\build\Vibrancy.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Projects\tmp\hyper-transparent\electron-vibrancy\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Projects\\tmp\\hyper-transparent\\electron-vibrancy\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! not ok
npm ERR! code 1
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "node-gyp rebuild"
```
</details>

**Comment by marmelin** [comment]
Same error with Windows 10 SDK (10.0.18362.0) & Windows 10 SDK (10.0.17763.0)

**Comment by marmelin** [comment]
Do I need to compile it with VS2017 or earlier?

**Comment by danielehrhardt** [comment]
Could you try: 
`npm install --global windows-build-tools`

**Comment by AydanGaite** [comment]
You need to install node version ```v6.17.1```. I used nvm to switch without uninstalling my current version of node.
If your on Mac you also need to install ```libstdc++``` which you can get by downloading the files from here:
https://github.com/miaozhang9/libstdc

**Comment by EriKWDev** [comment]
I'm also having problems installing on Windows 10.
```yaml
node_modules\electron-vibrancy\src\Vibrancy.cc(86,57): error C2660: 'v8::Value
::BooleanValue': function does not take 0 arguments [D:\Documents\Coding\GitHub\sveltelectron\node_modules\electron-vib
rancy\build\Vibrancy.vcxproj]
```

**Comment by DrunkWinter** [comment]
Fixed in my fork along with a cleanup and package updates. https://github.com/DrunkWinter/electron-vibrancy

**Comment by ttqftech** [comment]
> Fixed in my fork along with a cleanup, package updates and improvements. https://github.com/DrunkWinter/electron-vibrancy

@DrunkWinter 404 Page Not Found.

**Comment by danielehrhardt** [comment]
> Fixed in my fork along with a cleanup, package updates and improvements. https://github.com/DrunkWinter/electron-vibrancy

I am also interested.

**Comment by DrunkWinter** [comment]
> > Fixed in my fork along with a cleanup, package updates and improvements. https://github.com/DrunkWinter/electron-vibrancy
> 
> @DrunkWinter 404 Page Not Found.



> > Fixed in my fork along with a cleanup, package updates and improvements. https://github.com/DrunkWinter/electron-vibrancy
> 
> I am also interested.

@danielehrhardt @ttqftech I deleted the fork, because I noticed there was no real demand for it. 

Is there any particular reason why this: https://github.com/Seo-Rii/electron-acrylic-window from Seo-Rii is not good enough of a replacement? 

If there is a good reason for it I might consider putting it back up.

**Comment by diegozhu** [comment]
> > > Fixed in my fork along with a cleanup, package updates and improvements. https://github.com/DrunkWinter/electron-vibrancy
> > 
> > 
> > @DrunkWinter 404 Page Not Found.
> 
> > > Fixed in my fork along with a cleanup, package updates and improvements. https://github.com/DrunkWinter/electron-vibrancy
> > 
> > 
> > I am also interested.
> 
> @danielehrhardt @ttqftech I deleted the fork, because I noticed there was no real demand for it.
> 
> Is there any particular reason why this: https://github.com/Seo-Rii/electron-acrylic-window from Seo-Rii is not good enough of a replacement?
> 
> If there is a good reason, I might consider putting it back up.

extremely slow when drag.

**Comment by DrunkWinter** [comment]
> > > > Fixed in my fork along with a cleanup, package updates and improvements. https://github.com/DrunkWinter/electron-vibrancy
> > > 
> > > 
> > > @DrunkWinter 404 Page Not Found.
> > 
> > 
> > > > Fixed in my fork along with a cleanup, package updates and improvements. https://github.com/DrunkWinter/electron-vibrancy
> > > 
> > > 
> > > I am also interested.
> > 
> > 
> > @danielehrhardt @ttqftech I deleted the fork, because I noticed there was no real demand for it.
> > Is there any particular reason why this: https://github.com/Seo-Rii/electron-acrylic-window from Seo-Rii is not good enough of a replacement?
> > If there is a good reason, I might consider putting it back up.
> 
> extremely slow when drag.

This repository and my fork does not resolve this issue and we can't because we are bound under the limitations of Electron and Windows 10. However Windows 11 (dev/beta branch) seems to have somewhat resolved this issue.

**Comment by ralamiri** [comment]
Hi all, this is something fixed by reviewing [V8's documentation on the particular function](https://v8docs.nodesource.com/node-12.0/dc/d0a/classv8_1_1_value.html#a9b14a81dc04004a86965ea7e3106a21f)
It appears that in the `NAN_METHOD(Vibrancy::SetVibrancy) ` function, the `BooleanValue()` is missing an argument of type v8::Isolate*. This is easily fixed by amending the following line:  `bool toggleState = toggleStateObj->BooleanValue(isolate);`

I was able to make this fix, and get everything updated on my fork which is [available here](https://github.com/ralamiri/electron-vibrancy) for anyone interested. It's currently working on the latest version of Windows 10, and I'll also be testing/updating this on macOS to make sure it's working on that platform as well.

**Comment by arnavxjain** [comment]
Installing visual studio build tools will allow you to override the system and install the module manually. Give that a try. After that try installing with `--force` or `-g` for global

**Comment by Timfti** [comment]
Bro, it is now 2026. I used AI to analyze this. It is indeed useful. This error is no longer reported, but other errors are still there.   😅

👇
The reason why npm install failed this time was: C++ compilation error. Although the Visual Studio Build Tools were found and configured correctly, a specific compilation error was encountered while compiling the Vibrancy.cc file.

### Error analysis
The error message appears on line 86 of the Vibrancy.cc file:

```cpp
error C2660: "v8::Value::BooleanValue": function does not accept 0 arguments
This indicates that the code is calling the v8::Value::BooleanValue() method without passing an argument, but that version requires that one must be passed.
```
### Solution
Modify the Vibrancy.cc file
Open the src/Vibrancy.cc file, locate near line 86, and find the call to BooleanValue(). According to the V8 API documentation, the BooleanValue() method requires a v8::Isolate* parameter as the first parameter.

#### Before modification:
```cpp
bool toggleState = toggleStateObj->BooleanValue();
```
#### After modification:
```cpp
bool toggleState = toggleStateObj->BooleanValue(isolate);
where isolate is a handle to the current V8 instance, which should already be defined in the code.
```
### Recompile
After the modification is completed, rerun:
```bash
npm install
```
### Additional information
This error is caused by a V8 API version update. Newer versions of V8 require some methods to pass the Isolate parameter explicitly instead of getting it implicitly from the context.
If you cannot find the isolate variable when modifying your code, it should be a V8 isolate instance that is already in scope. You can refer to other places in your code that use the V8 API to get the correct isolate variable.
If you need more detailed help, you can check V8's official documentation or refer to other places in the project that use similar APIs.
